// LOCALHOST
### Get all contacts
GET http://localhost:8080/contacts


### Get contact by id
DELETE http://localhost:8080/contacts/648d3aaa537096bd00e045f0 HTTP/1.1


### Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT contact
PUT http://localhost:8080/contacts/648d5291d8df37feeb75608b HTTP/1.1
content-type: application/json

{
    "firstName":"Maryam",
    "lastName":"Waheed",
    "email":"test@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"12/12/20"
}
### DELETE contact
DELETE http://localhost:8080/contacts/648d5428d8df37feeb75608c HTTP/1.1

// PRODUCTION Deploy
### Get all contacts
GET https://cse341-project-2-6mta.onrender.com/contacts


### Get contact by id
GET https://cse341-project-2-6mta.onrender.com/contacts/622023f642f9ab4cd6e060b3


### Create contact
POST https://cse341-project-2-6mta.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT contact
PUT https://cse341-project-2-6mta.onrender.com/contacts/6220bcb39cd507e920c75a0b HTTP/1.1
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Birch",
    "email":"sarahB@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"06/12/20"
}


### DELETE contact
DELETE https://cse341-project-2-6mta.onrender.com/contacts/648d4c379ba3d19e4543b31d HTTP/1.1